app/blueprints/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, EmailField, FileField
from wtforms.validators import DataRequired, Length, EqualTo
from flask_wtf.file import FileAllowed


class LoginForm(FlaskForm):
    username = StringField(label='Username', validators=[DataRequired(), Length(min=1, max=128)]) 
    password = PasswordField(label='Password', validators=[DataRequired(), Length(min=1, max=64)])
    submit = SubmitField(label="Log In")


class RegisterForm(FlaskForm):
    username = StringField(label='Username', validators=[DataRequired(), Length(min=1, max=128)])
    email = EmailField(label='Email', validators=[DataRequired(), Length(max=128)])
    password = PasswordField(label='Password', validators=[DataRequired(), Length(min=1, max=64)])
    confirm_password = PasswordField(label='Confirm password', 
        validators=[EqualTo('password', message='Пароли должны совпадать')])
    submit = SubmitField(label="Register")


class ProfileEditForm(FlaskForm):
    username = StringField(label='Username', validators=[DataRequired(), Length(min=1, max=128)])
    email = EmailField(label='Email', validators=[DataRequired(), Length(max=128)])
    image = FileField(label='Change profile photo', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField(label="Save changes")

app/blueprints/accounts/views.py
from flask import Blueprint, redirect, render_template, session, url_for, request, flash, abort

from app.database import db
from .forms import *
from .db_queries import *
from app.blueprints.posts.db_queries import get_posts_of_user
from .utils import *

bp = Blueprint('accounts', __name__, url_prefix='/accounts')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            create_user(form.username.data, form.email.data, form.password.data)
            flash('You registered successfully', 'info')
            return redirect(url_for('accounts.login'))
        except Exception as ex:
            flash(str(ex), 'error')
            return redirect(url_for('accounts.register'))

    return render_template('accounts/register.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = get_user_by_username(form.username.data)
        if user and user.check_password(form.password.data):
            session['user_id'] = user.id
            return redirect('/')
        else:
            flash('Incorrect username or password', 'error')
            redirect(url_for('accounts.login'))
    
    return render_template('accounts/login.html', form=form)


@bp.route('/logout', methods=['POST'])
def logout():
    session.pop('user_id')
    return redirect(url_for('accounts.login'))


@bp.route('/profile/<int:user_id>', methods=['GET'])
@bp.route('/profile/<int:user_id>/<int:page>', methods=['GET'])
@login_required
def profile(user_id: int, page: int = 1):
    user = get_user_by_id(user_id)
    if not user:
        abort(404)

    current_user = get_current_user()
    posts = get_posts_of_user(user_id, page)

    return render_template(
        'accounts/profile.html', 
        user=user, 
        current_user=current_user, 
        posts=posts
    )
    

@bp.route('/profile_editor', methods=['GET', 'POST'])
@login_required
def profile_editor():
    user = get_current_user()
    form = ProfileEditForm(username=user.username, email=user.email)
    if form.validate_on_submit():
        try:
            update_user(user, form.username.data, form.email.data, form.image.data)
            flash('Profile changed successfully', 'info')
            return redirect(url_for('accounts.profile', user_id=session['user_id']))
        except Exception as ex:
            flash(str(ex), 'error')
            return redirect(url_for('accounts.profile_editor'))
    
    return render_template('accounts/profile_editor.html', form=form, user=user)


@bp.route('/remove_profile_photo', methods=['POST'])
@login_required
def remove_profile_photo(user_id: int):
    user = get_current_user()
    
    delete_profile_photo_user(user)
    flash('Profile photo deleted successfully', 'info')
    return redirect(url_for('accounts.profile_editor', user_id=user_id))


@bp.route('/follow/<int:user_id>', methods=['POST'])
@login_required
def follow(user_id: int):
    user = get_current_user()

    try:
        user_to_follow = set_following(user_id, True)
    except Exception as ex:
        flash(str(ex), 'error')
        return redirect(url_for('accounts.profile', user_id=user_id))

    flash(f'You are now {user_to_follow.username}\'s follower!', 'info')
    return redirect(url_for('accounts.profile', user_id=user_id))


@bp.route('/unfollow/<int:user_id>', methods=['POST'])
@login_required
def unfollow(user_id: int):
    user = get_current_user()

    try:
        user_to_unfollow = set_following(user_id, False)
    except Exception as ex:
        flash(str(ex), 'error')
        return redirect(url_for('accounts.profile', user_id=user_id))

    flash(f'Now you are not {user_to_unfollow.username}\'s follower!', 'info')
    return redirect(url_for('accounts.profile', user_id=user_id))

app/templates/accounts/login.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="form-container">
    {{ render_form(form) }}
</div>

{% endblock %}

app/templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}

<div class="profile-container">
    <div class="profile">
        <div class="profile-img">
            {% if user.profile_photo %}
            <img src="{{ url_for('static', filename=user.profile_photo) }}" alt="{{ user.username }}'s photo"
                style="width: 100%; border-radius:50%" />
            {% else %}
            <img src="{{ url_for('static', filename='images/avatars/default/avatar.png') }}"
                alt="{{ user.username }}'s photo" style="width: 100%; border-radius:50%" />
            {% endif %}
        </div>
        <div>
            <p>
            <h5>Profile info</h5>
            </p>
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Date of registration: {{ user.created_on | date_format }}</p>
            <p>Followers: {{ user.followers.count() }}, following: {{ user.followed.count() }} </p>
            {% if session['user_id'] == user.id %}
            <p>
                <a href="{{ url_for('accounts.profile_editor') }}">Edit profile</a>
                <form action="/accounts/logout" method="POST">
                    <button type="submit" class="btn btn-outline-danger">Log out</button>
                </form>
            </p>
            {% else %}
            {% if current_user.is_following(user) %}
            <form action="{{ url_for('accounts.unfollow', user_id=user.id) }}" method="POST">
                <input type="submit" value="Unfollow" />
            </form>
            {% else %}
            <form action="{{ url_for('accounts.follow', user_id=user.id) }}" method="POST">
                <input type="submit" value="Follow" />
            </form>
            {% endif %}
            {% endif %}
        </div>
    </div>

    {% if posts.items|length > 0 %}
    <h5>User's posts</h5>

    {% include "posts/posts_nav_profile.html" %}

    <div class="posts-container">
        {% for post in posts.items %}
        {% include "posts/post.html" %}
        {% endfor %}
    </div>

    {% include "posts/posts_nav_profile.html" %}
    {% else %}
    <h5>User have no posts</h5>
    {% endif %}
</div>



{% endblock %}

app/templates/accounts/profile_editor.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}Profile editor{% endblock %}

{% block content %}

<div class="profile-container">
    <div class="profile-editor-header">
        {% if user.profile_photo %}
        <img src="{{ url_for('static', filename=user.profile_photo) }}" alt="{{ user.username }}'s photo"
            class="profile-editor-img" />
        {% else %}
        <img src="{{ url_for('static', filename='images/avatars/default/avatar.png') }}"
            alt="{{ user.username }}'s photo" class="profile-editor-img" />
        {% endif %}
        <p>Your current photo</p>
    </div>
    {% if user.profile_photo %}
    <form action="/accounts/remove_profile_photo" method='post'>
        <input type="submit" value="Delete photo" />
    </form>
    {% endif %}
    {{ render_form(form) }}
</div>

{% endblock %}

app/templates/accounts/register.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}Registration{% endblock %}

{% block content %}

<div class="form-container">
    {{ render_form(form) }}
</div>

{% endblock %}