app/blueprints/posts/views.py
from flask import Blueprint, redirect, render_template, session, url_for, request, flash, jsonify
import os

from app.database import db
from .forms import *
from .db_queries import *
from app.blueprints.accounts.utils import *
from app.blueprints.accounts.db_queries import *

bp = Blueprint('posts', __name__, url_prefix='/posts')


@bp.route('/create_post', methods=['GET', 'POST'])
def create_post_view():
    form = CreatePostForm()
    if form.validate_on_submit():
        try:
            create_post(form.title.data, form.content.data, form.image.data)
            flash('Post created successfully', 'info')
            return redirect(url_for('index'))
        except Exception as ex:
            flash(str(ex), 'error')
            return redirect(url_for('posts.create_post_view'))

    return render_template('posts/create_post.html', form=form)


@bp.route('/like/<int:post_id>', methods=['POST'])
@login_required
def like(post_id: int):
    user = get_current_user()

    number_of_likes = like_post(user, post_id)

    return jsonify({ 'likes': number_of_likes })


@bp.route('/delete_like/<int:post_id>', methods=['POST'])
@login_required
def delete_like(post_id: int):
    user = get_current_user()

    number_of_likes = delete_like_post(user, post_id)

    return jsonify({ 'likes': number_of_likes })


@bp.route('/followed_posts', methods=['GET'])
@bp.route('/followed_posts/<int:page>', methods=['GET'])
@login_required
def followed_posts(page: int = 1):
    try:
        user = get_current_user()
        posts = user.get_followed_posts(page)
    except Exception as ex:
        print(ex)
        return redirect(url_for('accounts.login'))

    return render_template('posts/followed_posts.html', current_user=user, posts=posts)

app/templates/base.html
<!doctype html>
<html>

<head>
    <title>{% block title %}{% endblock %} - My social network</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='/css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/posts.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='/js/posts.js') }}"></script>
</head>

<body class="content">
    <header>
        {% include 'navbar.html' %}
    </header>

    {% for category, message in get_flashed_messages(with_categories=true) %}
    {% if category == 'info'%}
    <div class="alert alert-info">{{ message }}</div>
    {% else %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endif %}
    {% endfor %}

    {% block content %}{% endblock %}
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="posts-container">
    {% if user %}
    <h4>Welcome, {{ user.username }}!</h4>
    {% endif %}

    {% include "posts/posts_nav_index.html" %}

    {% for post in posts.items %}
    {% include "posts/post.html" %}
    {% endfor %}

    {% include "posts/posts_nav_index.html" %}
</div>

{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">My Social Network</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% if session['user_id'] %}
            <li class="nav-item active">
                <a class="nav-link" href="/">
                    Home
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.followed_posts') }}">
                    Following
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.create_post_view') }}">
                    Create post
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('accounts.profile', user_id=session['user_id']) }}">
                    Profile
                </a>
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('accounts.register') }}">
                    Register
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('accounts.login') }}">
                    Log In
                </a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav> 